services:
  db:
    image: postgres:16
    container_name: wallet-watcher-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - wallet_db_data:/var/lib/postgresql/data

volumes:
  wallet_db_data: